#!/bin/sh

set -e

echo "Running pre-commit hook..."

# COLORS
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Получаем текущую ветку
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

# Получаем список измененных файлов
CHANGED_FILES=$(git diff --cached --name-only)

if [ "$CURRENT_BRANCH" = "main" ] && echo "$CHANGED_FILES" | grep -qE '^(View|UI|Internal)/'; then
    echo "Changes in 'View/ | UI/ | Internal/' directory detected."

    echo -e "${GREEN}[|] Running formatted and build for View/ | UI/ | Internal/...${NC}"

    dotnet format tramptap.sln
    git add .
    echo -e "${GREEN}[+] Success formatted and build for View/ | UI/ | Internal/!${NC}"
elif echo "$CHANGED_FILES" | grep -qE '^(View|UI|Internal)/'; then
    echo "Changes in 'View/ | UI/ | Internal/' directory detected. Only formatting will be done."

    dotnet format tramptap.sln

    git add .
    echo -e "${GREEN}[+] Success formatted for client-mobile!${NC}"
else
    echo "No changes in 'View/ | UI/ | Internal/' directory. Skipping actions for View/ | UI/ | Internal/."
fi
